export const GET_USERS_START = 'USERS/GET_USERS_START';
export const GET_USERS_SUCCESS = 'USERS/GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'USERS/GET_USERS_ERROR';
export const SELECT_CURRENT_USER = 'USERS/SELECT_CURRENT_USER';
