export const GET_ALBUMS_START = 'ALBUMS/GET_ALBUMS_START';
export const GET_ALBUMS_SUCCESS = 'ALBUMS/GET_ALBUMS_SUCCESS';
export const GET_ALBUMS_ERROR = 'ALBUMS/GET_ALBUMS_ERROR';
export const SELECT_CURRENT_ALBUM = 'ALBUMS/SELECT_CURRENT_ALBUM';
